### ISSUE TITLE
adb not found in the path

### ISSUE THREAD

**Issue by clouths** [bitrise-steplib/steps-start-android-emulator#19]
**Affected version:** 1.0.1
**Issue:** The task is unable to find the program "adb" from Android platform-tools in the path. 
**bitrise.yml content:**

```
format_version: 1.1.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - BITRISE_PROJECT_PATH: build.gradle
    opts:
      is_expand: false
  - GRADLE_TASK: assembleDebug
    opts:
      is_expand: false
  - GRADLEW_PATH: "./gradlew"
    opts:
      is_expand: false
trigger_map:
- pattern: features/*
  is_pull_request_allowed: false
  workflow: Features/*
workflows:
  Features/*:
    steps:
    - activate-ssh-key:
        title: Activate App SSH key
        inputs:
        - ssh_key_save_path: "$HOME/.ssh/steplib_ssh_step_id_rsa"
    - git-clone: {}
    - create-android-emulator@0.9.1:
        inputs:
        - name: android-23
        - platform: android-23
    - start-android-emulator:
        inputs:
        - emulator_name: android-23
    - gradle-runner:
        title: Core Gradle Runner
        inputs:
        - gradle_file: "$BITRISE_PROJECT_PATH"
        - gradle_task: ":projectName:installDebugTest"
        - apk_file_include_filter: "*debugTest.apk"
        - apk_file_exclude_filter: |-
            *unaligned*.apk
            *debug.apk
    - gradle-runner:
        title: Test Gradle Runner
        inputs:
        - gradle_file: "$BITRISE_PROJECT_PATH"
        - gradle_task: ":subProjectName:connectedDebugTestAndroidTest"
        - apk_file_include_filter: ''
        - apk_file_exclude_filter: "*.apk"
        outputs:
        - BITRISE_APK_PATH: ''
          opts:
            title: Path of the generated APK
            description: |-
              This output will include the path of the generated APK,
              after filtering based on the filter inputs.

              If the build generates more than one APK which fulfills the
              filter inputs this output will contain the last one's path.
            summary: Path of the generated (and moved) APK - after filtering.
            is_required: false
            is_expand: true
            is_dont_change_value: false
            is_template: false
```

**Here is a part of the log from the website:**

```
+------------------------------------------------------------------------------+
| (3) create-android-emulator                                                  |
+------------------------------------------------------------------------------+
| id: create-android-emulator                                                  |
| version: 0.9.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-03-14T20:04:17Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
  name: android-23
  platform: android-23
  abi: armeabi-v7a
Check if platform installed
  Platform android-23 installed
Check if system image installed
  System image sys-img-armeabi-v7a-android-23 installed
Creating AVD image android-23
  AVD image android-23 ready to use 🚀
|                                                                              |
+----+--------------------------------------------------------------+----------+
| ✅  | create-android-emulator                                      | 9.8 sec  |
+----+--------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (4) start-android-emulator@1.0.1                                             |
+------------------------------------------------------------------------------+
| id: start-android-emulator                                                   |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-03-14T20:04:27Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
  emulator_name: android-23
/tmp/bitriseXXXXXXXXX/step_src/step.rb:139:in ``': No such file or directory - /opt/android-sdk-linux/platform-tools/adb (Errno::ENOENT)
    from /tmp/bitriseXXXXXXXXX/step_src/step.rb:139:in `<main>'
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | start-android-emulator@1.0.1 (exit code: 1)                  | 0.87 sec |
+----+--------------------------------------------------------------+----------+
ERRO[20:04:27] Step (start-android-emulator@1.0.1) failed, error: (exit status 1) 
| Issue tracker: ...ub.com/bitrise-steplib/steps-start-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-start-android-emulator      |
+----+--------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Thanks for the report! Indeed, we just checked and although `platform-tools` should be installed by Dockerfile it's not in the docker image.

We suspect this might be a Docker Hub issue (we have automated builds for this image there) - we'll investigate and probably move all of our docker image building to bitrise.io, instead of using Docker Hub's automated builds.

We'll notify you as soon as we find the cause of the issue, and we'll update the docker images this weekend, hopefully with preinstalled `platform-tools` this time.

**Comment by viktorbenei** [comment]
The issue seems to be **not** Docker Hub related, but to how `echo y | android update sdk ...` is performed. It seems that with the current version of the Android SDK this solution is no longer reliable if you have to accept **multiple** licenses. The first one will be accepted, but subsequent ones won't.

**Comment by viktorbenei** [comment]
The new configuration is now ready - we'll re-build the Docker image & update the bitrise.io Linux stack this Saturday.

**Comment by viktorbenei** [comment]
Additionally we now added a related test to `system_report.sh`, which will prevent new images to be created if `adb` is not found in the `platform-tools` folder.

**Comment by clouths** [comment]
Thank you for this fix, it is appreciated!

**Comment by viktorbenei** [comment]
Linux VMs are now updated, latest Docker images are pre-cached and the issue is fixed. You can find more information on our Blog: http://blog.bitrise.io/2016/03/19/linux-android-and-weekly-cache-updates.html

Once again sorry for the inconvenience, we made sure that this won't happen again (with the `system_report.sh` tests), and thanks for the detailed issue report!
